### ISSUE TITLE
iPhoneでメタマスクのアカウントと連携できない

### ISSUE THREAD

**Issue by mikkegt** [SingularitySociety/nounsmap-web#29]
iOSにMetamaskのアプリを入れました。入れたらnounsmapと連携できるのかと思ったのですが、
Userをクリックすると「Please install MetaMask」のメッセージが表示されます。
連携させるにはどうしたらよいでしょうか（もしくはこれから実装でしょうか）

確認したブラウザー

- iPhone12/Safari
- iPhone12/Chrome

**Comment by kozayupapa** [comment]
@mikkegt  ご指摘ありがとうございます。
mobile でwalletを利用するには、現状metamask のアプリ自体に付属しているブラウザを利用するしか方法がないようです。
<img width="386" alt="image" src="https://user-images.githubusercontent.com/3196383/173377010-5d6b1638-aaf5-4edc-83ed-6bc0d17aa2d8.png">

metamaskのブラウザでも動作することは確認していますので是非お試しください。
